# -*- coding: utf-8 -*-
{
    'name': "BSI Bank Connection",
    'author': 'Botspot Infoware Pvt. Ltd.',
    'category': 'BSI Bank',
    'summary': """ Upload and parse BAI files""",
    'website': 'https://www.botspotinfoware.com',
    'company': 'Botspot Infoware Pvt. Ltd.',
    'maintainer': 'Botspot Infoware Pvt. Ltd.',
    'description': """ Upload and parse BAI files """,
    'version': '19.0',
    'depends': ['base', 'bsi_subway_base'],
    'data': [
        'security/ir.model.access.csv',
        'data/ir.cron.xml',
        'views/bsi_bank_accounts.xml',
        'views/bsi_bank_statements.xml',
        'views/bsi_sftp_files.xml',
        'views/bsi_bank_transactions.xml',
        'views/mapping.xml',
        'views/res_config_setting.xml',
    ],
    # 'images': ['static/description/Banner.gif'],
    'license': 'LGPL-3',
    # 'price': 59.00,
    'currency': 'USD',
    'installable': True,
    'application': True,
}
